/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vendingmachine;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void constructorTest() {
        App app = new App();
        assertNotNull(app);
    }
}
