/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vendingmachine;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class DataManagerTest {
    @Test
    public void constructorTest() {
        DataManager DM = new DataManager();
        assertNotNull(DM);
    }

    @Test
    public void innerClassTest(){
        DataManager DM = new DataManager();
        DataManager.Product p = DM.new Product("god", "Godiva", "Chocolate", 10, 7);
        DataManager.CreditCard c = DM.new CreditCard("Tester", "1234567");
        DataManager.Account a = DM.new Account("abscdfe", "ahenma", "buyer");
        assertNotNull(p);
        assertNotNull(c);
        assertNotNull(a);
    }

    @Test
    public void productClassTest(){
        DataManager DM = new DataManager();
        DataManager.Product p = DM.new Product("god", "Godiva", "Chocolate", 10, 7);
        assertEquals("god", p.getId());
        assertEquals("Godiva", p.getName());
        assertEquals("Chocolate", p.getCategory());
        assertEquals(10, p.getQuantity());
        assertEquals(7, p.getPrice());
    }

    @Test
    public void cardClassTest(){
        DataManager DM = new DataManager();
        DataManager.CreditCard c = DM.new CreditCard("Tester", "1234567");
        assertEquals("Tester", c.getCardHolder());
        assertEquals("1234567", c.getCardNumber());
    }

    @Test
    public void accountClassTest() {
        DataManager DM = new DataManager();
        DataManager.Account a = DM.new Account("abscdfe", "ahenma", "buyer");
        assertEquals("abscdfe", a.getUsername());
        assertEquals("ahenma", a.getPassWord());
        assertEquals("buyer", a.getRole());
    }

    @Test
    public void productsTest() {
        DataManager DM = new DataManager();
        DataManager.Product p = DM.new Product("god", "Godiva", "Chocolate", 10, 7);
        assertTrue(DM.fetchProducts());
        assertTrue(DM.flushProducts());
        assertTrue(DM.printProducts());
        assertNotNull(DM.getProducts());
        // assertTrue(DM.addProduct("lin", "Lindt", "Chocolate", 10, 7));
        // // Test add product in false condition
        // assertFalse(DM.addProduct("aaa", "test", "Test", -10, 7));
        // assertFalse(DM.addProduct("aaa", "test", "Test", 10, -7));
    }

    @Test
    public void creditCardsTest() {
        DataManager DM = new DataManager();
        DataManager.CreditCard c = DM.new CreditCard("Tester", "1234567");
        assertTrue(DM.fetchCreditCards());
        assertTrue(DM.flushCreditCards(c));
        assertNotNull(DM.getCreditCards());
        assertTrue(DM.addCreditCard("Testerr", "123456"));
    }

    @Test
    public void accountTest(){
        DataManager DM = new DataManager();
        DataManager.Account a = DM.new Account("abscdfe", "ahenma", "buyer");
        assertTrue(DM.fetchAccounts());
        assertTrue(DM.printAccounts());
        assertTrue(DM.flushAccounts(a));
        assertTrue(DM.addAccount("acdfe", "anma", "buyer"));
    }
}
