/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vendingmachine;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ProcessingLogicTest {
    @Test
    public void constructorTest() {
        ProcessingLogic PL = new ProcessingLogic();
        assertNotNull(PL);
        assertNotNull(PL.getUser());
        assertNotNull(PL.getRole());
    }

    @Test
    public void buyLogicTest() {
        ProcessingLogic PL = new ProcessingLogic();

        String[] cancel = {"buy", "spr*1", "coc*1", "cash", "$20*5", "cancel"};
        String[] valid1 = {"buy", "spr*1", "coc*1", "jui*1", "cash", "$20*2", "50c*20"};
        String[] valid2 = {"buy", "mm*7", "cash", "$10*1"};
        String[] valid3 = {"buy", "mm*1", "cash", "$1*1", "50c*1", "20c*1", "10c*1", "5c*1"};
        String[] valid4 = {"buy", "spr*1", "coc*1", "jui*1", "card", "Ruth", "55134"};
        String[] invalid0 = {"buy"};
        String[] invalid1 = {"buy", "spr*1"};
        String[] invalid2 = {"buy", "spr*1", "coc*1"};
        String[] invalid3 = {"buy", "spr*1", "coc*1", "jui*1"};
        String[] invalid4 = {"buy", "lol*1", "coc*1", "jui*1", "cash", "$20*2", "50c*20"};
        String[] invalid5 = {"buy", "spr*1", "lol*1", "jui*1", "cash", "$20*2", "50c*20"};
        String[] invalid6 = {"buy", "spr*1", "coc*1", "lol*1", "cash", "$20*2", "50c*20"};
        String[] invalid7 = {"buy", "spr*1", "coc*1", "jui*1", "lol", "$20*2", "50c*20"};
        String[] invalid8 = {"buy", "spr*1", "coc*1", "jui*1", "cash", "lol", "50c*20"};
        String[] invalid9 = {"buy", "spr*1", "coc*1", "jui*1", "cash", "$20*2", "lol"};
        String[] invalid10 = {"buy", "spr*1", "coc*1", "jui*1", "card"};
        String[] invalid11 = {"buy", "spr*1", "coc*1", "jui*1", "card", "LOL"};
        String[] invalid12 = {"buy", "spr*1", "coc*1", "jui*1", "card", "LOL", "55134"};
        String[] invalid13 = {"buy", "spr*1", "coc*1", "jui*1", "card", "Ruth", "LOL"};
        String[] invalid14 = {"buy", "spr*999", "cash", "$100*100"};
        String[] invalid15 = {"buy", "spr*1", "cash", "50c*1"};
        String[] invalid16 = {"buy", "cash", "cash", "cash"};
        String[] invalid17 = {"buy", "card", "card", "card"};

        assertTrue(PL.buyLogic(cancel));
        assertTrue(PL.buyLogic(valid1));
        assertTrue(PL.buyLogic(valid2));
        assertTrue(PL.buyLogic(valid3));
        assertTrue(PL.buyLogic(valid4));
        assertFalse(PL.buyLogic(invalid0));
        assertFalse(PL.buyLogic(invalid1));
        assertFalse(PL.buyLogic(invalid2));
        assertFalse(PL.buyLogic(invalid3));
        assertFalse(PL.buyLogic(invalid4));
        assertFalse(PL.buyLogic(invalid5));
        assertFalse(PL.buyLogic(invalid6));
        assertFalse(PL.buyLogic(invalid7));
        assertFalse(PL.buyLogic(invalid8));
        assertFalse(PL.buyLogic(invalid9));
        assertFalse(PL.buyLogic(invalid10));
        assertFalse(PL.buyLogic(invalid11));
        assertFalse(PL.buyLogic(invalid12));
        assertFalse(PL.buyLogic(invalid13));
        assertFalse(PL.buyLogic(invalid14));
        assertFalse(PL.buyLogic(invalid15));
        assertFalse(PL.buyLogic(invalid16));
        assertFalse(PL.buyLogic(invalid17));
         
        
    }
}
